import React from "react";
import {
  FaRegFileAlt,
  FaStream,
  FaStar,
  FaGopuram,
  FaPodcast,
  FaFileSignature,
  FaBell,
  FaShoppingBag,
  FaWallet,
  FaHome,
  FaUserEdit,
  FaAdversal,
  FaStore,
  FaUsers,
  FaCircle,
  FaCog,
  FaQuestionCircle,
  FaSlidersH,
  FaUser,
  FaShoppingCart,
  FaGift,
  FaProductHunt,
  FaList,
  FaCode,
  FaCodeBranch,
  FaCircleNotch,
} from "react-icons/fa";
import * as Icon from "react-feather";
import { BsImage } from "react-icons/bs";
import { MdOutlineFolderSpecial } from "react-icons/md";
import { GiWantedReward } from "react-icons/gi";
import { CiDiscount1 } from "react-icons/ci";
import { TbTruckDelivery } from "react-icons/tb";
import { AiFillBell } from "react-icons/ai";
import { FiBarChart2 } from "react-icons/fi";

// eslint-disable-next-line no-sparse-arrays
const navigationConfig = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "item",
    icon: <FaHome size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/dashboard",
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Customers Managment",
  //   title: "Customers",
  // },
  {
    id: "Customer",
    title: "Customers",
    type: "collapse",
    icon: <FaUsers size={15} />,
    children: [
      {
        id: "createstaff",
        title: "Create staff",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/account/CreateAccount",
      },
      {
        id: "CustomerRegistration",
        title: "Customer Registration",
        type: "item",
        icon: <FaUserEdit size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/Customer/Customer_Registration",
      },
      {
        id: "Staffsearch",
        title: "Search",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/userlist",
      },

      {
        id: "Assign Role",
        title: "Assign Role",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/account/addRoleNew",
      },
      {
        id: "Role Search",
        title: "Role List",
        type: "item",
        icon: <FaUsers size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/Trupee/account/RoleList",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "System Managment",
  //   title: "System Managment",
  // },
  {
    id: "systemManagment",
    title: "System Managment",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "import",
        title: "Import",
        type: "item",
        icon: <MdOutlineFolderSpecial size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/SchedulerTime",
      },

      {
        id: "Spare Part",
        title: "Spare Part",
        type: "item",
        icon: <FaList size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/SparePartsSystem",
      },

      {
        id: "orders",
        title: "Orders",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/OrdersSystem",
      },

      {
        id: "PartsCatelog",
        title: "Parts Catelogue",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/PartCatalougue",
      },

      {
        id: "Invoice/Billing",
        title: "Invoice/Billing",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/InVoiceSystem",
      },
      {
        id: "supports",
        title: "Supports",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/SupportsSystem",
      },
      {
        id: "service",
        title: "Service",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/ServiceSystem",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Quotation MANAGEMENT",
  //   title: "Quotation",
  // },
  {
    id: "Quotation",
    title: "Quotation",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "Add Supplier",
        title: "Add Supplier",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/AddSupplier",
      },
      {
        id: "Create Quote",
        title: "Create Quote",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/CreateQuote",
      },
      {
        id: "Create Notes",
        title: "Create Notes",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/CreateNotes",
      },
      {
        id: "Debit Notes",
        title: " Debit Notes",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/DebitNotes",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Product Managment",
  //   title: "Product Managment",
  // },
  {
    id: "Product Managment",
    title: "Product Managment",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "Product Registration",
        title: "Product Registration",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/product/ProductRegistration",
      },
      {
        id: "Product Search",
        title: "Product Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/product/ProductSearch",
      },
      {
        id: "createCampaign",
        title: "Campaign Creation",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/createCampaign",
      },
      {
        id: "CampaignList",
        title: "Campaign Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/Campaignlist",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Parts Management",
  //   title: "Parts",
  // },

  {
    id: "Parts",
    title: "Parts",
    type: "collapse",
    icon: <FaList size={15} />,
    children: [
      {
        id: "Parts Catalogue",
        title: "Parts Catalogue",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/PartCatalougue",
      },
      {
        id: "Parts Search",
        title: "Parts Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/parts/PartList",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Order Management",
  //   title: "Order Management",
  // },
  {
    id: "order",
    title: "Order Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "partOrder",
        title: "Part Order",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/placeorder",
      },
      {
        id: "OrderSearch",
        title: "Order Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/order/placeorder",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "BILLINGS",
  //   title: "BILLINGS",
  // },
  {
    id: "BILLINGS",
    title: "BILLINGS",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "addtax",
        title: "Add tax",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/AddTaxSoft",
      },
      {
        id: "Courier/Shipping Charges",
        title: "Courier/Shipping Charges",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softnumen/CourierShipping",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Warranty Management",
  //   title: "Warranty Management",
  // },
  {
    id: "Warranty create",
    title: "Warranty",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "CreateWarrenty",
        title: "Create Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/createWarrenty",
      },
      {
        id: "Warranty Search",
        title: "Warranty Search",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/SearchWarrenty",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Ticketing Tool",
  //   title: "Ticketing Tool",
  // },
  {
    id: "Ticket",
    title: "Ticket",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "CreateTicket",
        title: "Create Ticket",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        // navLink: "/app/softNumen/warranty/createWarrenty",
      },
      {
        id: "TicketSearch",
        title: "Ticket Search",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        // navLink: "/app/softNumen/warranty/SearchWarrenty",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Scrutiny/Inspections",
  //   title: "Inspections",
  // },
  {
    id: "Inspections",
    title: "Scrutiny/Inspections",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Create Inspections",
        title: "Create Inspections",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/CreateWiki",
      },

      {
        id: "InspectionsSearch",
        title: "Inspections Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/ScrutinySystem",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Product Wiki",
  //   title: "Product Wiki",
  // },
  {
    id: "Product",
    title: "Product",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Publish WIKI",
        title: "Publish WIKI",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/CreateWiki",
      },
      {
        id: "WIKI Search",
        title: "WIKI Search",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/WikiList",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "WAREHOUSE MANAGEMENT",
  //   title: "WAREHOUSE",
  // },
  {
    id: "WAREHOUSE",
    title: "WAREHOUSE",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "CreateWarehouse",
        title: " Create Warehouse",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/WareHouseListSoft",
      },
      {
        id: "WarehouseSearch",
        title: " Warehouse Search",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/system/WareHouseListSoft",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Warranty Claims",
  //   title: "Warranty Claims",
  // },
  {
    id: "Warranty Claims",
    title: "Warranty Claims",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "OEM Warranty",
        title: "OEM Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/OEMWarranty",
      },
      {
        id: "Supplier Warranty",
        title: "Suppier Warranty",
        type: "item",
        icon: <FaList size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/warranty/SupplierWarranty",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Stock Management",
  //   title: "Stock Management",
  // },

  {
    id: "Stock Management",
    title: "Stock Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Stock Report",
        title: "Stock Report",
        type: "item",
        icon: <FaProductHunt size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/stockReport",
      },

      {
        id: "Stock Transfer",
        title: "Stock Transfer",
        type: "item",
        icon: <FaProductHunt size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/StockTransfer",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Product Policies",
  //   title: "Policies",
  // },
  {
    id: "Policy",
    title: " Policy",
    type: "collapse",
    icon: <FaProductHunt size={8} />,
    children: [
      {
        id: "CreatePolicy",
        title: "Create Policy",
        type: "item",
        icon: <FaPodcast size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/SoftNumen/policy/CreatePolicy",
      },
      {
        id: "ExtendedPolicy",
        title: "Extended Policy",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        // navLink: "/app/softNumen/ticketing/PendingService",
      },
      {
        id: "AMC",
        title: "AMC",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        // navLink: "/app/softNumen/ticketing/PendingService",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Reports Management",
  //   title: "Reports Management",
  // },
  {
    id: "Reports Management",
    title: "Reports Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "AdminReport",
        title: "Admin Report",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/cart/DateWiseReport",
      },
      {
        id: "Customer Report",
        title: "Customer Report",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/CustomerReports",
      },
      {
        id: "Staff Report",
        title: "Staff Report",
        type: "item",
        icon: <BsImage size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/StaffReport",
      },

      {
        id: "Product Report",
        title: "Product Report",
        type: "item",
        icon: <FaProductHunt size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/report/ProductReports",
      },
      {
        id: "Transaction Report",
        title: "Transaction Report",
        type: "item",
        icon: <FaCodeBranch size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/cart/BranchwiseReport",
      },
    ],
  },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Promotion Management",
  //   title: "Promotion Management",
  // },
  {
    id: "Promotion Management",
    title: "Promotion Management",
    type: "collapse",
    icon: <FaShoppingCart size={15} />,
    children: [
      {
        id: "Promotion",
        title: "Promotion",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/promotion/Promotion",
      },
      {
        id: "Discount&Coupon",
        title: "Discount&Coupon",
        type: "item",
        icon: <FaCode size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/softNumen/promotion/DiscountCoupon",
      },
    ],
  },

  // {
  //   type: "groupHeader",
  //   groupTitle: "SUPPORT MANAGEMENT",
  // },

  {
    id: "Supportcreate",
    title: "Support Create",
    type: "item",
    icon: <FaCog size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/softNumen/warranty/CreateSupport",
  },
  {
    id: "Supportsearch",
    title: "Support search",
    type: "item",
    icon: <FaCog size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/softNumen/warranty/SupportSearch",
  },
  {
    id: "helpAndSupport",
    title: "Help And Support",
    type: "item",
    icon: <FaQuestionCircle size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/softNumen/support/HelpandSupports",
  },
  {
    id: "logout",
    title: "Logout",
    type: "item",
    icon: <Icon.ArrowRight size={15} />,
    permissions: ["admin", "editor"],
  },
];
export default navigationConfig;
